TestTask.Web/ViewModels/SaleReportItemViewModel.cs
using System;
using System.Linq;
using System.Threading.Tasks;

namespace TestTask.Web.ViewModels
{
    public class SaleReportItemViewModel
    {
        public int OrderNum { get; set; }

        public string OrderDate { get; set; }

        public int ProductNum { get; set; }

        public string ProductName { get; set; }

        public Int16 Quantity { get; set; }

        public decimal UnitPrice { get; set; }
    }
}

TestTask.Web/ViewModels/SaleReportViewModel.cs
using System.Collections.Generic;

namespace TestTask.Web.ViewModels
{
    public class SaleReportViewModel
    {
        public SaleReportViewModel()
        {
            Items = new List<SaleReportItemViewModel>();
        }
        public string BeginDate { get; set; }

        public string EndDate { get; set; }

        public List<SaleReportItemViewModel> Items { get; set; }
    }
}

TestTask.Web/Controllers/ReportController.cs
using System;
using System.Linq;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using TestTask.ExcelExport;
using TestTask.Services;
using TestTask.Web.ViewModels;

namespace TestTask.Web.Controllers
{
    public class ReportController : Controller
    {
        private readonly ISaleReportBuilder _saleReportBuilder;
        private readonly IReportService _reportService;
        private readonly IMapper _mapper;

        public ReportController(ISaleReportBuilder saleReportBuilder, IReportService reportService, IMapper mapper)
        {
            _saleReportBuilder = saleReportBuilder;
            _reportService = reportService;
            _mapper = mapper;
        }

        public IActionResult Index()
        {
            var viewModel = new SaleReportViewModel();

            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Result(string beginDate, string endDate)
        {
            var viewModel = new SaleReportViewModel()
            {
                BeginDate = beginDate,
                EndDate = endDate,
                Items = _reportService.GetSaleReport(beginDate==null? (DateTime?)null: DateTime.Parse(beginDate), 
                                                    endDate == null ? (DateTime?)null : DateTime.Parse(endDate))
                        .Select(_mapper.Map<SaleReportItemViewModel>)
                        .ToList()
            };
            return View("Index", viewModel);
        }


        public ActionResult Export(string beginDate, string endDate)
        {
            var data = _reportService.GetSaleReport(beginDate == null ? (DateTime?)null : DateTime.Parse(beginDate), endDate == null ? (DateTime?)null : DateTime.Parse(endDate)).ToList();
            _saleReportBuilder.MakeExport(data);
            var caption = "Отчет по продажам";
            if (beginDate != null)
                caption += $" с {DateTime.Parse(beginDate):dd.MM.yyyy}";
            if (endDate != null)
                caption += $" по {DateTime.Parse(endDate):dd.MM.yyyy}";
            return File(_saleReportBuilder.MakeExport(data), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", caption + ".xlsx");
        }


        public IActionResult Error()
        {
            return View();
        }
    }
}

TestTask.Web/Views/Report/Index.cshtml
@{
}
@model SaleReportViewModel

<h1> Отчет по продажам</h1>

<div class="panel panel-info">
    <div class="panel-heading">Параметры</div>
    <div class="panel-body">
        <form role="form" class="form-inline" method="post" action="@Url.Action("Result")">
                <label>Период </label>
            <div class="form-group">
                <label for="inputBeginDate">с</label>
                <input type="date" class="form-control" id="inputBeginDate" placeholder="с" name="beginDate" value="@Model.BeginDate">
            </div>
            <div class="form-group">
                <label for="inputEndDate">по</label>
                <input type="date" class="form-control" id="inputEndDate" placeholder="по" name="endDate" value="@Model.EndDate">
            </div>
            <button type="submit" class="btn btn-primary">Применить</button>
        </form>
    </div>
</div>

@if (Model.Items.Count > 0)
{
<div class="panel panel-success">
    <div class="panel-heading">Результаты</div>
    <div class="panel-body">
        <div style="max-height: 400px; overflow-y: auto">
            <table class="table table-striped ">
                <thead> <tr style="font-weight: bold">
                    <td>Номер заказа</td>
                    <td>Дата заказа</td>
                    <td>Артикул товара</td>
                    <td>Наименование товара</td>
                    <td>Количество реализованных единиц товара</td>
                    <td>Цена реализации за единицу продукции</td>
                </tr>
                </thead>
                <tbody>
                @foreach (var item in Model.Items)
                {
                    <tr>
                        <td>@item.OrderNum</td>
                        <td>@item.OrderDate</td>
                        <td>@item.ProductNum</td>
                        <td>@item.ProductName</td>
                        <td>@item.Quantity</td>
                        <td>@item.UnitPrice</td>

                    </tr>

                }
                    </tbody> 
            </table>
          </div>
    </div>
    <div class="panel-footer"><button type="button" class="btn btn-primary" id="btnExport">Экспорт в Excel</button></div>
</div>
}

@section Scripts {
    <script type="text/javascript"> 
        $(document).ready(function () {
            $('#btnExport').click(function () {
                window.open("@Url.Action("Export")?beginDate=@Model.BeginDate&endDate=@Model.EndDate", "_blank");
            });

        });
    </script>
}

TestTask.Web/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Тестовое задание</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Report" asp-action="Index" class="navbar-brand">Тестовое задание</a>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - Дервель М.В.</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>